name: roomies_frontend
description: Frontend for the Roomies project.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  http: ^1.1.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true